language: cpp
dist: trusty

addons:
  apt:
    packages:
      - cmake
      - lcov
      - libpcap-dev
      - libboost-program-options-dev
      - libboost-system-dev

# Install dependencies
before_install:
  - .travis/install_dependencies

# Run cmake to prepare build
before_script:  
  - mkdir build
  - cd build
  - cmake ..

# Build and run tests/generate coverage
script: make && make check

# Submit coverage report to coveralls
after_success:
  - coveralls-lcov final.coverage
